musicbot:
  image: szastupov/musicbot
  restart: always
  links:
    - mongo
  environment:
    - BOT_NAME=pizza_musicbot
    - API_TOKEN=230590121:AAH7FBCnecUxEeawoWjaOwdQPd5woTAm4Cw
    - BOTAN_TOKEN=Optional botan token
    - MONGO_HOST=mongo
mongo:
  image: mongo
  restart: always
